FROM node:20-slim
RUN corepack enable && corepack prepare pnpm@9 --activate
WORKDIR /app
ARG NEXT_PUBLIC_APP_URL
ARG OST_GITHUB_ID
ARG OST_GITHUB_SECRET
ARG OST_REPO_SLUG
ARG OST_REPO_BRANCH
ARG OST_REPO_OWNER
ARG OST_CONTENT_PATH
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV OST_GITHUB_ID=$OST_GITHUB_ID
ENV OST_GITHUB_SECRET=$OST_GITHUB_SECRET
ENV OST_REPO_SLUG=$OST_REPO_SLUG
ENV OST_REPO_BRANCH=$OST_REPO_BRANCH
ENV OST_REPO_OWNER=$OST_REPO_OWNER
ENV OST_CONTENT_PATH=$OST_CONTENT_PATH
COPY package.json ./
RUN pnpm install
COPY . .
RUN pnpm build
EXPOSE 3000
CMD ["node", ".next/standalone/server.js"]
